---
- name: Install Elasticsearch
  hosts: localhost
  remote_user: root
  become: yes
  vars:
    home_address: /home/ec2-user/elasticsearch

  tasks:
    - name: Install Java 8
      command: yum install -y java-1.8.0

    - name: Remove Java 7
      command: yum remove -y java-1.7.0-openjdk

    - name: Move elasticsearch.repo into yum.repos.d
      copy:
        src: "{{ home_address }}/elasticsearch.repo"
        dest: /etc/yum.repos.d
        owner: root
        group: root
        mode: 000755

    - name: Install elasticsearch
      command: yum install -y elasticsearch

    - name: Configure Elasticsearch to start automatically when the system boots up
      command: chkconfig --add elasticsearch

    - name: Install x-pack
      command: /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack

    - name: Move privatekey.key
      copy:
        src: "{{ home_address }}/privateKey.key"
        dest: /etc/elasticsearch
        owner: root
        group: root
        mode: 000755

    - name: Move certificate.crt
      copy:
        src: "{{ home_address }}/certificate.crt"
        dest: /etc/elasticsearch
        owner: root
        group: root
        mode: 000755

    - name: Move elasticsearch.yml
      copy:
        src: "{{ home_address }}/elasticsearch.yml"
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: root
        mode: 000755

    - name: Gather facts
      ec2_facts:

    - name: Add line to the elastisearch.yml
      lineinfile:
       path: /etc/elasticsearch/elasticsearch.yml
       line: 'discovery.zen.ping.unicast.hosts: ["{{ ansible_ec2_public_ipv4 }}"]'

    - name: Move elasticsearch.yml
      copy:
        src: "{{ home_address }}/elasticsearch.yml"
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: root
        mode: 000755

    - name: Install Ec2 discovery plugin
      command: /usr/share/elasticsearch/bin/elasticsearch-plugin install discovery-ec2

    - name: Start Elasticsearch
      service:
         name: elasticsearch
         state: started